version: "3.9"

services:

  redis:
    image: "redis:alpine"

  web:
    build: .
    image: carogomezt/django_redis_demo
    environment:
      - APP_MODE=api
    env_file:
      - .env
    volumes:
      - .:/code
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on: 
      - redis

  cdn:
    image: nginx:latest
    container_name: django_cdn
    ports:
      - "8080:8000"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - web

  
