apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 8000
    # targetPort: 8000
  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - image: djangoredisdemoacr.azurecr.io/djangoredisdemo:v1
        name: django-app
        env:
          - name: APP_MODE
            value: "api"
        envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-configmap
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
            - mountPath: /static
              name: django-statics
      volumes:
      - name: django-statics
        persistentVolumeClaim:
          claimName: django-storage-claim