apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 20M
